# Developed by Alvaro Chao-Ecija

# Several functions have been developed, according to the proposed
# strategy by Seth for MVAR validation. The functions allow corrections
# for multiple comparisons offered by p.adjust.methods. The bonferroni
# correction has been selected as default, as suggested by Seth. 

# Therefore, these functions evaluate the stationarity of the 
# signals. They also test if the residuals of the MVAR model are
# white-noise, and evaluate the stability of the model.
#
# References: ---------------------------------------------------
#
#
#
# Seth AK. A MATLAB toolbox for Granger causal connectivity analysis. J 
# Neurosci Methods. 2010;186(2):262-73.
#
# Seth AK. Granger Causal Conectivity Analysis: A MATLAB Toolbox. 2011.
#
# Ding M, Bressler S, Yang W, Liang H. Short-window spectral analysis of cortical 
# event-related potentials by adaptative multivariate autoregressive modelling: data
# preprocessing, model validation, and variability assessment. Biol Cybern. 2000;83:35-45



CheckStationarity <- function(x, alpha = 0.05, lags = NULL, warnings = TRUE,
  verbose = FALSE, correction = "bonferroni"){
   N <- dim(x)[1]
   M <- dim(x)[2]
   if(is.null(lags)){
      lags <- sqrt(N)
   }
   adf_p_vals <- double(M)
   kpss_p_vals <- double(M)
   w <- getOption("warn")   
   options(warn = -1)
   for(m in 1:M){
       adf_p_vals[m] <- tseries::adf.test(x[,m], k = lags)$p.value
       kpss_p_vals[m] <- tseries::kpss.test(x[,m])$p.value
   }
   options(warn = w)
   adf_p_vals <- p.adjust(adf_p_vals, correction)
   kpss_p_vals <- p.adjust(kpss_p_vals, correction)
   non_sig_adf <- (1:M)[adf_p_vals > alpha]
   sig_kpss <- (1:M)[kpss_p_vals <= alpha]
   if(sum(sig_kpss) != 0){
      if(warnings){
      warning(paste("\n", "Time series", sig_kpss, "is not stationary", "\n"))
      }
      return(FALSE)
   } else if(sum(non_sig_adf) != 0){
      if(warnings){
      warning(paste("\n", "ADF testing suggest non stationarity for time series", non_sig_adf,
       "\n"))
      }
      if(sum(sig_kpss) != 0){
         if(warnings){
         warning(paste("\n", "Time series", sig_kpss, "is not stationary", "\n"))
         }
         return(FALSE)
      } else {
      if(warnings){
      warning(paste("Time series are stationary according to KPSS test"))
      }
      return(TRUE)
      }
   } else {
      if(verbose){
         return("Time series are stationary")
      } else {
         return(TRUE)
      }
   }
}




DiagnoseResiduals <- function(model, alpha = 0.05, correction = "bonferroni",
   verbose = FALSE){
    lms <- model$varresult
    p_vals <- double(length(lms))
    for(n in 1:length(lms)){
        mod <- lms[[n]]
        p_vals[n] <- lmtest::dwtest(mod)$p
    }
    p_vals <- p.adjust(p_vals, correction)
    if(verbose & (min(p_vals) <= alpha)){
       print("Residuals are not white processes")
    } else if(verbose & (min(p_vals) > alpha)){
       print("Model residuals are white processes")
    } else {
       return(min(p_vals) > alpha)
    }
}




DiagnoseStability <- function(model, do.plot = FALSE, verbose = FALSE){
    roots <- vars::roots(model)
    if(do.plot) PlotRoots(model)
    if(verbose & !(TRUE %in% (roots >= 1))){
       print("The model is stable")
    } else if(verbose & !(TRUE %in% (roots < 1))){
       print("The model is not stable")
    } else {
       return(!(TRUE %in% (roots >= 1)))
    }
}

PlotRoots <- function(model, col = "blue", col2 = "red"){
  roots <- vars::roots(model, FALSE)
  plot(Re(roots), Im(roots), xlim = c(-1.2, 1.2), ylim = c(-1.2, 1.2), col = col)
  lines(seq(-1, 1, len = 1000), sqrt(1 - seq(-1, 1, len = 1000)^2))
  lines(seq(-1, 1, len = 1000), -sqrt(1 - seq(-1, 1, len = 1000)^2))
}



roots2 <- function(x, modulus = TRUE) 
{
    if (!(class(x) == "varest")) {
        stop("\nPlease provide an object of class 'varest', generated by 'VAR()'.\n")
    }
    K <- x$K
    p <- x$p
    A <- Acoef(x)
    sigma <- summary(x)$cov
    a0 <- GetA0Fun(sigma)$a0
    for(n in 1:length(A)){
        A[[n]] <- solve(a0) %*% A[[n]]
    }
    A <- unlist(A)
    companion <- matrix(0, nrow = K * p, ncol = K * p)
    companion[1:K, 1:(K * p)] <- A
    if (p > 1) {
        j <- 0
        for (i in (K + 1):(K * p)) {
            j <- j + 1
            companion[i, j] <- 1
        }
    }
    roots <- eigen(companion)$values
    if (modulus) 
        roots <- Mod(roots)
    return(roots)
}













